version: '3.5'

services:
  alita-partner-portal-frontend_build:
    build: ../
    container_name: 'alita-partner-portal-frontend_build'
    volumes:
      - dist:/usr/src/app/dist

  alita-partner-portal-frontend_web:
    image: nginx
    ports:
      - 80:80
    container_name: 'alita-partner-portal-frontend_web'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist:
